openapi: 3.0.1
info:
  title: LoccanaMasterUserAccessSubmenus
  description: API Definition of LoccanaMasterUserAccessSubmenus
  version: 1.0.0
servers:
- url: http://localhost:8290/loccana/master/user_access_submenus
paths:
  /:
    post:
      responses:
        default:
          description: Default response
  /{id}:
    get:
      parameters:
      - name: id
        in: path
        required: true
        style: simple
        explode: false
        schema:
          type: string
      responses:
        default:
          description: Default response
    put:
      parameters:
      - name: id
        in: path
        required: true
        style: simple
        explode: false
        schema:
          type: string
      requestBody:
        description: Sample Payload
        content:
          application/json:
            schema:
              type: object
              properties:
                payload:
                  type: object
        required: false
      responses:
        default:
          description: Default response
    delete:
      parameters:
      - name: id
        in: path
        required: true
        style: simple
        explode: false
        schema:
          type: string
      responses:
        default:
          description: Default response
